---
# Credentials
asa_satellite_admin_username: admin
asa_satellite_admin_password: redhat123
asa_satellite_username: "{{ satellite_admin_username }}"
asa_satellite_password: "{{ satellite_admin_password }}"
asa_satellite_installer_verbose: true
asa_satellite_installer_scenario: "{{ satellite_installer_scenario }}"
asa_satellite_installer_options: "{{ satellite_installer_options }}"

# Administration
asa_satellite_timezone: UTC
asa_satellite_data_device: /dev
asa_satellite_validate_certs: false

# System/OS related
asa_satellite_min_cpu_count: 4
# Size must be integer, MB
asa_satellite_min_memory_size: 20240
# Size must be integer, GB
asa_satellite_data_disk_min_size: 500
# Size must be integer, GB
asa_satellite_min_pulp_size: 300
# Size must be integer, GB
asa_satellite_min_pgsql_size: 20
asa_satellite_server_basearch: "x86_64"
asa_satellite_os_version: "9"
asa_satellite_deployment_version: "6.16"
