---
# Basic Settings
satellite_settings:
  - name: "default_download_policy"
    value: "immediate"
  - name: "default_redhat_download_policy"
    value: "immediate"
  - name: "default_proxy_download_policy"
    value: "immediate"
  - name: "errata_status_installable"
    value: "true"
  - name: "unregister_delete_host"
    value: "true"
  - name: "template_sync_associate"
    value: "never"
  - name: "template_sync_branch"
    value: "master"
  - name: "template_sync_repo"
    value: "{{ satellite_giturl }}"
  - name: "template_sync_force"
    value: "true"
  - name: "template_sync_lock"
    value: "true"
  - name: "administrator"
    value: "{{ satellite_email }}"
  - name: "db_pending_seed"
    value: "false"
  - name: "entries_per_page"
    value: "100"
  - name: "unregister_delete_host"
    value: "true"
  - name: "remote_execution_workers_pool_size"
    value: "100"
  - name: "ignored_interface_identifiers"
    value: ["lo", "en*v*", "usb*", "vnet*", "_vdsmdummy_", "veth*", "docker*", "tap*", "qbr*", "qvb*", "qvo*", "qr-*", "qg-*", "vlinuxbr*", "vovsbr*", "bond*"]
  - name: "host_tasks_workers_pool_size"
    value: "100"
  - name: "login_text"
    value: "Sample login text."
  - name: "unattended_url"
    value: "https://{{ ansible_fqdn }}"
...
