---
- name: Manage host collections on Disconnected Satellite
  hosts: disconnected_satellites
  gather_facts: true
  become: true

  tasks:
    - name: Include manage host collections task from the role
      ansible.builtin.include_role:
        name: satellite_operations
        tasks_from: manage_host_collections.yml
...
