---
- name: Manage content credentials on connected Satellite
  hosts: connected_satellite
  gather_facts: true
  become: true
  vars_files:
    - roles/satellite_operations/vars/main.yml

  tasks:
    - name: Skip playbook if variables are not defined
      when: satellite_content_credentials_connected is not defined or satellite_content_credentials_connected | length <= 0
      ansible.builtin.meta: end_play

    - name: Include manage content credentials task from the role
      ansible.builtin.include_role:
        name: satellite_operations
        tasks_from: manage_content_credentials.yml

- name: Manage content credentials on disconnected Satellite
  hosts: disconnected_satellites
  gather_facts: true
  become: true
  vars_files:
    - roles/satellite_operations/vars/main.yml

  tasks:
    - name: Skip playbook if variables are not defined
      when: satellite_content_credentials_disconnected is not defined or satellite_content_credentials_disconnected | length <= 0
      ansible.builtin.meta: end_play

    - name: Include manage content credentials task from the role
      ansible.builtin.include_role:
        name: satellite_operations
        tasks_from: manage_content_credentials.yml

...
