---
- name: Manage Red Hat repositories on connected Satellite
  hosts: connected_satellite
  gather_facts: true
  become: true
  vars_files:
    - ../roles/satellite_operations/vars/main.yml

  tasks:
    - name: Include manage repos task from the role
      ansible.builtin.include_role:
        name: satellite_operations
        tasks_from: manage_repos.yml

- name: Manage Red Hat repositories on disconnected Satellite
  hosts: disconnected_satellites
  gather_facts: true
  become: true
  vars_files:
    - ../roles/satellite_operations/vars/main.yml

  tasks:
    - name: Include manage repos task from the role
      ansible.builtin.include_role:
        name: satellite_operations
        tasks_from: manage_repos.yml
...
