---
- name: Manage content view version on Disconnected Satellite
  hosts: disconnected_satellites
  gather_facts: true
  become: true

  tasks:
    - name: Include manage content view versions task from the role
      ansible.builtin.include_role:
        name: satellite_operations
        tasks_from: manage_content_view_version.yml
...
