---
- name: Register a client on Satellite
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Include register client task from the role
      ansible.builtin.include_role:
        name: satellite_client_operations
        tasks_from: register_client.yml
...
