---
- name: Update capsule server
  hosts: capsules
  gather_facts: true
  become: true
  vars:
    satellite_whitelist_options: non-rh-packages

  tasks:
    - name: Unset release version
      ansible.builtin.shell: subscription-manager release --unset

    - name: Gather info on installed packages on Disconnected satellite
      ansible.builtin.package_facts:
        manager: auto
      delegate_to: "{{ satellite_disconnected }}"

    - name: Verify Satellite version of Disconnected satellite
      ansible.builtin.set_fact:
        satellite_disconnected_current_version: "{{ ansible_facts.packages['satellite'][0].version }}"
      when: "'satellite' in ansible_facts.packages"
      delegate_to: "{{ satellite_disconnected }}"

    - name: Gather info on installed packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Set variable for current Capsule version
      ansible.builtin.set_fact:
        capsule_current_version: "{{ ansible_facts.packages['satellite-capsule'][0].version }}"
      when: "'satellite-capsule' in ansible_facts.packages"

    - name: Assert that Disconnected version > capsule version
      ansible.builtin.assert:
        that: satellite_disconnected_current_version >= capsule_current_version
        fail_msg: "Connected Satellite must be updated first. Perform the update before rerunning this job"

    - name: Update Satellite-Maintain if needed
      ansible.builtin.package:
        name: rubygem-foreman_maintain
        state: latest

    - name: Perform a health check
      ansible.builtin.shell: "satellite-maintain update check --assumeyes --whitelist={{ satellite_whitelist_options }}"
      environment:
        TMOUT: 0
      retries: 3
      delay: 5
      register: result
      until: result is not failed

    - name: Update Capsules
      ansible.builtin.shell: "satellite-maintain update run --assumeyes --whitelist={{ satellite_whitelist_options }}"
      environment:
        TMOUT: 0

    - name: Stop Satellite services
      ansible.builtin.shell: satellite-maintain service stop

    - name: Reboot server
      ansible.builtin.reboot:
        reboot_timeout: 3600
...
