name: Run ansible-lint
on: push
#  pull_request:
#    branches: ["main", "stable", "release/v*"]
jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
